// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/evgenytr/metrics.git/internal/mockgen (interfaces: StorageGen)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	metric "github.com/evgenytr/metrics.git/internal/metric"
	gomock "github.com/golang/mock/gomock"
)

// MockStorageGen is a mock of StorageGen interface.
type MockStorageGen struct {
	ctrl     *gomock.Controller
	recorder *MockStorageGenMockRecorder
}

// MockStorageGenMockRecorder is the mock recorder for MockStorageGen.
type MockStorageGenMockRecorder struct {
	mock *MockStorageGen
}

// NewMockStorageGen creates a new mock instance.
func NewMockStorageGen(ctrl *gomock.Controller) *MockStorageGen {
	mock := &MockStorageGen{ctrl: ctrl}
	mock.recorder = &MockStorageGenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageGen) EXPECT() *MockStorageGenMockRecorder {
	return m.recorder
}

// GetCounterValue mocks base method.
func (m *MockStorageGen) GetCounterValue(arg0 context.Context, arg1 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounterValue", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounterValue indicates an expected call of GetCounterValue.
func (mr *MockStorageGenMockRecorder) GetCounterValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounterValue", reflect.TypeOf((*MockStorageGen)(nil).GetCounterValue), arg0, arg1)
}

// GetGaugeValue mocks base method.
func (m *MockStorageGen) GetGaugeValue(arg0 context.Context, arg1 string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGaugeValue", arg0, arg1)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGaugeValue indicates an expected call of GetGaugeValue.
func (mr *MockStorageGenMockRecorder) GetGaugeValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGaugeValue", reflect.TypeOf((*MockStorageGen)(nil).GetGaugeValue), arg0, arg1)
}

// GetMetricsMap mocks base method.
func (m *MockStorageGen) GetMetricsMap(arg0 context.Context) (map[string]*metric.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricsMap", arg0)
	ret0, _ := ret[0].(map[string]*metric.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricsMap indicates an expected call of GetMetricsMap.
func (mr *MockStorageGenMockRecorder) GetMetricsMap(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsMap", reflect.TypeOf((*MockStorageGen)(nil).GetMetricsMap), arg0)
}

// InitializeMetrics mocks base method.
func (m *MockStorageGen) InitializeMetrics(arg0 context.Context, arg1 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeMetrics", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeMetrics indicates an expected call of InitializeMetrics.
func (mr *MockStorageGenMockRecorder) InitializeMetrics(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeMetrics", reflect.TypeOf((*MockStorageGen)(nil).InitializeMetrics), arg0, arg1)
}

// ListAll mocks base method.
func (m *MockStorageGen) ListAll(arg0 context.Context) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", arg0)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockStorageGenMockRecorder) ListAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockStorageGen)(nil).ListAll), arg0)
}

// Ping mocks base method.
func (m *MockStorageGen) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockStorageGenMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockStorageGen)(nil).Ping), arg0)
}

// ReadValue mocks base method.
func (m *MockStorageGen) ReadValue(arg0 context.Context, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadValue", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadValue indicates an expected call of ReadValue.
func (mr *MockStorageGenMockRecorder) ReadValue(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadValue", reflect.TypeOf((*MockStorageGen)(nil).ReadValue), arg0, arg1, arg2)
}

// StoreMetrics mocks base method.
func (m *MockStorageGen) StoreMetrics(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreMetrics", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreMetrics indicates an expected call of StoreMetrics.
func (mr *MockStorageGenMockRecorder) StoreMetrics(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreMetrics", reflect.TypeOf((*MockStorageGen)(nil).StoreMetrics), arg0)
}

// Update mocks base method.
func (m *MockStorageGen) Update(arg0 context.Context, arg1, arg2, arg3 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockStorageGenMockRecorder) Update(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStorageGen)(nil).Update), arg0, arg1, arg2, arg3)
}

// UpdateCounter mocks base method.
func (m *MockStorageGen) UpdateCounter(arg0 context.Context, arg1 string, arg2 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCounter", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCounter indicates an expected call of UpdateCounter.
func (mr *MockStorageGenMockRecorder) UpdateCounter(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCounter", reflect.TypeOf((*MockStorageGen)(nil).UpdateCounter), arg0, arg1, arg2)
}

// UpdateGauge mocks base method.
func (m *MockStorageGen) UpdateGauge(arg0 context.Context, arg1 string, arg2 float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGauge", arg0, arg1, arg2)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGauge indicates an expected call of UpdateGauge.
func (mr *MockStorageGenMockRecorder) UpdateGauge(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGauge", reflect.TypeOf((*MockStorageGen)(nil).UpdateGauge), arg0, arg1, arg2)
}
